version: '3'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - '1433:1433'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S database -U sa -P "reallyStrongPwd123" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
      
  web:
    image: netflicks:1.0
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8081:80'
    volumes:
      - ./contrast_security_protect.yaml:/etc/contrast/dotnet-core/contrast_security.yaml
    environment:
      - ConnectionStrings__DotNetFlicksConnection=Server=tcp:database,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;
      - CORECLR_PROFILER_PATH_64=/opt/contrast/contentFiles/any/netstandard2.0/contrast/runtimes/linux-x64/native/ContrastProfiler.so
      - CORECLR_PROFILER={8B2CE134-0948-48CA-A4B2-80DDAD9F5791}
      - CORECLR_ENABLE_PROFILING=1
      - CONTRAST_CORECLR_LOGS_DIRECTORY=/opt/contrast/
      - CONTRAST__SERVER__NAME=contrast-protect-demo
volumes:
  mysql-data:
